export const CHECKINGSESSIONSTATUS = 0
export const NOOPENSESSIONYETSESSIONSTATUS = 1
export const SESSIONRUNNINGSESSIONSTATUS = 2
export const RUNNINGTOOLONGSESSIONSTATUS = 3
export const USEDBYANOTHERCASHIERSESSIONSTATUS = 4

export const UNDECIDEDUSECASHMANAGEMENT = 0
export const ENABLEUSECASHMANAGEMENT = 1
export const SKIPUSECASHMANAGEMENT = 2
export const DISABLEUSECASHMANAGEMENT = 3
